import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/layouts/header";
import { MainNav } from "@/components/layouts/nav";
import { siteConfig } from "@/config/site";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased" >
                <Header />
                <MainNav items={siteConfig.mainNav}/>
                {children}
            </body>
        </html>
    );
}
